# Generated by Django 4.2.6 on 2023-10-24 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni', '0002_rename_student_id_students_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_ID',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_student_ID', message='Student ID must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
